using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Repositary;
using Clinic_Management_System;


/*
 * wanted to make a simple client console code with less number of instructions or codes to make it crystal clear ,so all the validations are done in repositary class
 * All the declared methods in the Library are Defined in the Repositary class.
 * All the Business logics are done in the Repositary class,
 * All the methods and business logics of the client console needed are defined in the Repositary class
 * All the user inputs are validated in the Repositary class with special constraints
 * All the inputs are got from the user in the Repositary class file, apart from the Action choosings in the home menu like "add patient" which is done here
 * every input is validated whether it is in correct format and In range and meaningful in the Repositary class
 * Every method is defined as Empty argument method and all the validation is done in the Repositary class, such that Console .EXE need not do any validation
 * All the doctors are Present for the whole day from 10AM to 4PM.
 * Every time when user enter the details He/She is given 2 chances to enter the data, as sometimes due to typing error the data may be not in correct format,
   so when ever the system thinks that the entered data is not in the correct format it makes the user know and gives one more chance to enter,
   only if the 2nd attempt also ends as failure, control return to main menu.
*/


namespace Clinic_Management_System_Repositary
{
    internal class Client_ClinicManagementSystem
    {
        public static void Main()
        {
            

            string UserName,Password;
            I_Admin_Menu admin_menu = new Admin_Menu();
            I_Home_Menu home_menu = new Home_Menu();
            I_Login_Menu login_menu = new Login_Menu();

            bool exit_status = true;


            //If the user id or password is incorrect the console end its program for security purpose
            //console starts from the Login menu for users(Front end staff of the clinic),
            //If the username is "admin", and password is "admin@123" , it takes user to the Admin menu where add user or add doctor operations can be performed
            //Only authorized persons or Developer or the management can perform the above tasks
            //Users Username will not be "admin" in any case as it is Admin user id and user's username is generated by system 
            //user can be in the logged in screen(Home Menu) until he/she logs out
            //User has options to end the program or logoff the System using Exit option at any time

            do
            {
                exit_status = true;
                Console.WriteLine("\n..........................WELCOME TO Sabari Clinic.......................  \n");
                Console.WriteLine("           Login:\n\nUser name:    ");
                UserName = Console.ReadLine();
                if (UserName == "admin")
                {
                    Console.WriteLine("Password:    ");
                    Password = Console.ReadLine();


                    //If the username is "admin", and password is "admin@123" , it takes user to the Admin menu where add user or add doctor operations can be performed
                    //Only authorized persons or Developer or the management can perform the above tasks


                    if (Password == "admin@123")
                    {
                        do
                        {

                            Console.Write("\n\n\n\n\n\n           Admin Menu\n\n   1.Add a User  \n    2.Add a Doctor    \n     3.Logout    \n\nPlease enter your choice......");
                            int choice1 = 0;
                            try
                            {
                                choice1 = Convert.ToInt32(Console.ReadLine());
                            }
                            catch (FormatException)
                            {
                                Console.WriteLine("please enter only numbers from 1 to 3");
                                try
                                {
                                    choice1 = Convert.ToInt32(Console.ReadLine()); //  
                                }
                                catch (FormatException)
                                {
                                    Console.WriteLine("\n your input is not valid . Try again after sometimes.....");

                                    break;
                                }

                            }
                            if ((choice1 > 0) && (choice1 < 4))
                            {
                                if (choice1 == 1)
                                    admin_menu.Add_User();
                                else if (choice1 == 2)
                                    admin_menu.Add_Doctors();
                                else
                                    break;

                            }
                            else
                            {
                                Console.WriteLine("\n\nInvalid choice......Please try after sometimes....");
                                break;
                            }

                        } while (true);



                    }
                    else
                    {
                        Console.WriteLine("\n\nIncorrect Password.....Please try after some times.......");
                        break;
                    }
                        
                }



                //only authorized users can enter into home menu

                else 
                {
                    if (login_menu.Username_check(UserName) == true)
                    {
                        Console.WriteLine("Password:    ");
                        Password = Console.ReadLine();
                        if (login_menu.Password_check(UserName, Password) == true)
                        {

                            
                            int choice = 0;
                            do
                            {
                                Console.WriteLine("\n\n\n\n\n\n\n               Clinic Management System              \n\n");
                                Console.WriteLine("\n Choose anyone below: \n\t1.View Doctors \n\t2.Add Patient \n\t3.Schedule Appointment \n\t4.Cancel Appointment \n\t5.Logout  \n\t6.exit  \n\n Please enter your choice .......");

                                try
                                {
                                    choice = Convert.ToInt32(Console.ReadLine());
                                }
                                catch (FormatException)
                                {
                                    Console.WriteLine("please enter only numbers from 1 to 6");
                                    try
                                    {
                                        choice = Convert.ToInt32(Console.ReadLine()); //  
                                    }
                                    catch (FormatException)
                                    {
                                        Console.WriteLine("\n your input is not valid . Try again after sometimes.....");

                                        break;
                                    }

                                }

                                switch (choice)
                                {
                                    case 1:
                                    {
                                            home_menu.View_Doctors();
                                            break;
                                    }
                                    case 2:
                                    {
                                            home_menu.Add_Patient();
                                            break;
                                    }
                                    case 3:
                                    {
                                            home_menu.Schedule_Appointment();
                                            break;
                                    }
                                    case 4:
                                    {
                                            Console.Write("\nPlease enter Patient Id.......");
                                            string Patient_id=Console.ReadLine();
                                            home_menu.Cancel_Appointment(Patient_id);
                                            break;
                                    }
                                    case 5:
                                        break;
                                    case 6:
                                    {
                                            exit_status = false;
                                            break;
                                    }
                                    default:
                                    {
                                            Console.WriteLine("  ................. Invalid choice ................");
                                            break;
                                    }
                                }
                                if (choice == 6)
                                    break;
                                if (choice == 5)
                                    break;

                            } while (choice!=5);









                        }
                        else
                        {
                            Console.WriteLine("\n\nIncorrect Password.....Try after some times.....");
                            break;
                        }
                            
                    }
                    else 
                    {
                        Console.WriteLine("\n\nUser name does not Exist.....Try after some times.....");
                        break;
                    }
                }

            } while(exit_status);
            
        }

    }
}
